name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache functions/node_modules
        uses: actions/cache@v2
        id: cache-functions-node_modules
        with:
          path: functions/node_modules
          key: ${{ runner.os }}-${{ hashFiles('functions/yarn.lock') }}

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm -g i yarn
      - run: yarn install --frozen-lockfile && yarn --cwd functions install --frozen-lockfile
      - run: yarn lint && yarn test:rport && yarn build:functions
      - name: Set src/conf/version.ts
        run: grep '"version"' package.json | sed -e "s/.*:\s*\"/export default '/" -e "s/\"\s*,*\s*$/';/" > src/conf/version.ts
      - run: |
          yarn functions:config:set \
            initial.email="${{ secrets.INITIAL_EMAIL }}" \
            initial.password="${{ secrets.INITIAL_PASSWORD }}" \
            initial.url="${{ secrets.INITIAL_URL }}" \
            --token "${{ secrets.FIREBASE_TOKEN_AMBER_CASE }}"
      - run: |
          yarn deploy --only storage,firestore,functions --force \
            --token "${{ secrets.FIREBASE_TOKEN_AMBER_CASE }}"
      - name: Set src/conf/firebase.ts
        run: sed 's/FIREBASE_API_KEY/${{ secrets.FIREBASE_API_KEY_AMBER_CASE }}/' -i src/conf/firebase.ts
      - run: yarn build
      - name: Set build/version.json
        run: grep '"version"' package.json | sed -e 's/^\s*/{/' -e 's/,*\s*$/}/' > build/version.json
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AMBER_CASE }}'
          channelId: live
          projectId: amber-case
      - run: curl https://asia-northeast1-amber-case.cloudfunctions.net/api/setup
