name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache functions/node_modules
        uses: actions/cache@v2
        id: cache-functions-node_modules
        with:
          path: functions/node_modules
          key: ${{ runner.os }}-${{ hashFiles('functions/yarn.lock') }}

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm -g i yarn
      - run: yarn install --frozen-lockfile && yarn --cwd functions install --frozen-lockfile
      - run: yarn lint && yarn test
      - name: Set src/conf/version.ts
        run: grep '"version"' package.json | sed -e "s/.*:\s*\"/export default '/" -e "s/\"\s*,*\s*$/';/" > src/conf/version.ts
      - name: Set src/conf/firebase.ts
        run: sed 's/FIREBASE_API_KEY/${{ secrets.FIREBASE_API_KEY_AMBER_CASE }}/' -i src/conf/firebase.ts
      - run: yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AMBER_CASE }}'
          projectId: amber-case
